### ISSUE TITLE
Animate: Save Video? 

### ISSUE THREAD

**Issue by Dekita** [ai-dock/comfyui#5]
Hi, I've been playing around with the animate provisioning script and it all works well apart from, when i try to set the output format to any type of video rather than gif i get the following error: 
```
2023-10-27 22:08:21 /opt/micromamba/envs/comfyui/bin/ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
2023-10-27 22:08:21 ERROR:root:!!! Exception during processing !!!
2023-10-27 22:08:21 ERROR:root:Traceback (most recent call last):
2023-10-27 22:08:21   File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
2023-10-27 22:08:21     output_data, output_ui = get_output_data(obj, input_data_all)
2023-10-27 22:08:21   File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
2023-10-27 22:08:21     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-10-27 22:08:21   File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
2023-10-27 22:08:21     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-10-27 22:08:21   File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 195, in combine_video
2023-10-27 22:08:21     proc.stdin.write(frame.tobytes())
2023-10-27 22:08:21 BrokenPipeError: [Errno 32] Broken pipe
```

Hoping there is an easy solution to add the missing lib? Unfortunately I'm not able to figure out how to do it myself :(

**Comment by robballantyne** [comment]
Hi

Could you try running `micromamba -n comfyui install openh264=2.1.0 -c defaults -y`

It'll downgrade the installed version from 2.1.1 to 2.2.0 which provides the library you need

**Comment by Dekita** [comment]
ran the command in dockerhub using exec, restarted, still getting the same error :(
wonder if that was the correct way you meant for me to run the command? 
also wondering if maybe its an issue directly with the animatediff nodes.

**Comment by robballantyne** [comment]
Ah sorry, you'd need to run that command from a running container, or you could add it at the top of the provisioning script. If it fixes the issue I'll add it into the animate script.

I don't want to do it in the build because it's a torch dependency and I don't want to risk breaking anything else  (unlikely as it is)

**Comment by robballantyne** [comment]
This is now fixed as the underlying PyTorch image has had ffmpeg updated to a newer version that won't fail on dependencies.
