### ISSUE TITLE
RuntimeError: Unexpected error from cudaGetDeviceCount()

### ISSUE THREAD

**Issue by KalleLeskinen** [ai-dock/comfyui#52]
I'm getting a cuda when running the default jupyter template on Vast.Ai 

```
Starting ComfyUI...
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or
- Make your system-wide implementation visible by installing ocl-icd-system conda package.
** ComfyUI startup time: 2024-03-02 21:15:23.498445
** Platform: Linux
** Python version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
** Python executable: /opt/micromamba/envs/comfyui/bin/python
** Log path: /opt/ComfyUI/comfyui.log
Prestartup times for custom nodes:
   0.0 seconds: /opt/ComfyUI/custom_nodes/ComfyUI-Manager
Traceback (most recent call last):
  File "/opt/ComfyUI/main.py", line 76, in
    import execution
  File "/opt/ComfyUI/execution.py", line 11, in
    import nodes
  File "/opt/ComfyUI/nodes.py", line 20, in
    import comfy.diffusers_load
  File "/opt/ComfyUI/comfy/diffusers_load.py", line 3, in
    import comfy.sd
  File "/opt/ComfyUI/comfy/sd.py", line 4, in
    from comfy import model_management
  File "/opt/ComfyUI/comfy/model_management.py", line 118, in
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/opt/ComfyUI/comfy/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
/opt/ai-dock/bin/supervisor-comfyui.sh: line 17:   831 Killed                  /usr/bin/python3 /opt/ai-dock/fastapi/logviewer/main.py -p $LISTEN_PORT -r 5 -s "${SERVICE_NAME}" -t "Preparing ${SERVICE_NAME}"  (wd: /root)
```

**Comment by robballantyne** [comment]
Looks like that machine doesn't support cuda>=11.8.0

Have you tried another instance?
