### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fonts/truetype'

### ISSUE THREAD

**Issue by SoaringTiger** [ai-dock/comfyui#54]
``` 
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
supervisor-1  | Traceback (most recent call last):
supervisor-1  |   File "/opt/ComfyUI/server.py", line 420, in get_object_info
supervisor-1  |     out[x] = node_info(x)
supervisor-1  |   File "/opt/ComfyUI/server.py", line 398, in node_info
supervisor-1  |     info['input'] = obj_class.INPUT_TYPES()
supervisor-1  |   File "/opt/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 467, in INPUT_TYPES
supervisor-1  |     file_list = [f for f in os.listdir(font_dir) if os.path.isfile(os.path.join(font_dir, f)) and f.lower().endswith(".ttf")]
supervisor-1  | FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fonts/truetype'
```

--------
I now solve the problem by manually copy it
```
docker cp /usr/share/fonts/truetype/dejavu containerID:/usr/share/fonts/truetype
```

**Comment by santosh** [comment]
I am having the same problem on Arch Linux. It says:

    [ERROR] An error occurred while retrieving information for the 'CR Select Font' node.

when trying to load ComfyUI-Manager.

Did anyone find a fix?

**Comment by robballantyne** [comment]
Fonts now included in base image
