### ISSUE TITLE
 Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by minifisk** [ai-dock/comfyui#6]
I'm getting the error " Found no NVIDIA driver on your system." when spinning up this image on my Mac M1, any ideas on how to fix it? 

```
Traceback (most recent call last):
  File "/opt/ComfyUI/main.py", line 72, in <module>
    import execution
  File "/opt/ComfyUI/execution.py", line 12, in <module>
    import nodes
  File "/opt/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/opt/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "/opt/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/opt/ComfyUI/comfy/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/opt/ComfyUI/comfy/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Starting ComfyUI...
** ComfyUI start up time: 2023-10-31 10:39:32.162144

Prestartup times for custom nodes:
   0.0 seconds: /opt/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/opt/ComfyUI/main.py", line 72, in <module>
    import execution
  File "/opt/ComfyUI/execution.py", line 12, in <module>
    import nodes
  File "/opt/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/opt/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "/opt/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/opt/ComfyUI/comfy/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/opt/ComfyUI/comfy/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/opt/micromamba/envs/comfyui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Starting ComfyUI...
```

**Comment by robballantyne** [comment]
Hi

Unfortunately I have no hardware to test builds for Apple, so I don't yet support them. I would like to, but for now I can only build for amd64 with NVIDIA and ROCm.

**Comment by robballantyne** [comment]
I believe it's not removing the error but rather it's delaying the error until the workspace sync completes - It's a slow process that's only really meant to be used with cloud provider network storage.

When that process completes you'll encounter the same issue as ComfyUI begins it's startup procedure.

If the Nvidia drivers are not found it's likely that the [Nvidia container runtime](https://developer.nvidia.com/nvidia-container-runtime) is not installed correctly.
