### ISSUE TITLE
PermissionError some custom nodes

### ISSUE THREAD

**Issue by telestia** [ai-dock/comfyui#81]
I installed some custom_nodes in Dockerfile and I got PermissionError while run image. Can you help me how can I fix this?

Traceback (most recent call last):
  File "/opt/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "", line 883, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 6, in 
    from .glob import manager_server
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1698, in 
    core.write_config()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 217, in write_config
    with open(config_path, 'w') as configfile:
PermissionError: [Errno 13] Permission denied: '/opt/ComfyUI/custom_nodes/ComfyUI-Manager/config.ini'

Cannot import /opt/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: [Errno 13] Permission denied: '/opt/ComfyUI/custom_nodes/ComfyUI-Manager/config.ini'
Traceback (most recent call last):
  File "/opt/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "", line 883, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/__init__.py", line 10, in 
    if init():
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.py", line 161, in init
    log("Init")
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.py", line 21, in log
    if not always and not is_logging_enabled():
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.py", line 14, in is_logging_enabled
    config = get_extension_config()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.py", line 76, in get_extension_config
    shutil.copy(default_config_path, config_path)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.json'

Cannot import /opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts module for custom nodes: [Errno 13] Permission denied: '/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/pysssss.json'
Exception in thread Thread-1 ():
Traceback (most recent call last):
  File "/opt/micromamba/envs/comfyui/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/micromamba/envs/comfyui/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1694, in 
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "/opt/micromamba/envs/comfyui/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/micromamba/envs/comfyui/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1691, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1681, in get_cache

Import times for custom nodes:
   0.0 seconds: /opt/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /opt/ComfyUI/custom_nodes/comfy-plasma
   0.0 seconds: /opt/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /opt/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /opt/ComfyUI/custom_nodes/ComfyUI_essentials
   0.1 seconds (IMPORT FAILED): /opt/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /opt/ComfyUI/custom_nodes/efficiency-nodes-comfyui
    
with open(cache_uri, "w", encoding='utf-8') as file:
PermissionError: [Errno 13] Permission denied: '/opt/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json'
Starting server

**Comment by robballantyne** [comment]
You'll probably need to run `/opt/ai-dock/bin/fix-permissions` after installing the nodes - The Dockerfile runs in root user context but the ComfyUI service runs in a normal user context; Usually `user` (`1000:1000`) but the UID/GID can vary depending on the owner of any mounted volume at `/workspace`

**Comment by telestia** [comment]
Thank you for answer. I try to add /opt/ai-dock/bin/fix-permissions but I got same error after add to the my Dockerfile with RUN command its work fine. But I wonder if the reason why I get the same error while inside the provisioning file is because the provisioning file is also run with normal user privileges?

**Comment by matbeedotcom** [comment]
@robballantyne Any idea where to best have "/opt/ai-dock/bin/fix-permissions" execute if a permission error occurs?
